# Generated by Django 3.2 on 2022-11-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
    ]
